### ISSUE TITLE
Create a Dashboard layout of the escrow

### ISSUE THREAD

**Issue by SwineCoder101** [SwineCoder101/encode-solana-bootcamp-project#14]
Create a Dashboard layout of the escrow. This will show user balances, escrow configuration data, deposit widget, withdraw widget, vault balances

**Comment by Vivekjoshi11** [comment]
created PR for this (https://github.com/SwineCoder101/encode-solana-bootcamp-project/pull/17) check if this ui looks good or any changes needed?
